### ISSUE TITLE
Where did it save the files?

### ISSUE THREAD

**Issue by rafaelgou** [Ryeeeeee/MarkdownX#9]
Hi,

I'm trying to copy the files from mobile device to PC through USB cable, mounting, but I can't find the files I've created.

Where does it save the files? Is there a place where I can set this? I've found Dropbox cached files, but not local ones.

Thanks! Great app!

**Comment by Ryeeeeee** [comment]
You can find local files on `/sdcard/Android/data/com.ryeeeeee.markdownx/files/notes`

**Comment by rafaelgou** [comment]
Thanks, man! Found it.

**Comment by rvestal** [comment]
How do I open an existing file in a different folder?
